services:
    nginx:
        build:
            dockerfile: .deployment/docker/nginx/Dockerfile
        networks:
            - api
        depends_on:
            - api
        ports:
            - "80:80"

    api:
        build:
            dockerfile: .deployment/docker/php/Dockerfile
        environment:
            APP_URL: http://api.local
        volumes:
            - "./:/app"
        networks:
            - api

    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
        ports:
            - "5432:5432"
        networks:
            - api

networks:
    api:
